# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f02bc4f4bdeafaee5a88c331cc0f9c0c10702cd113dd134e1fdaae510fbc77743debf1df569da1abade01e2e486a715a9ac0d5c48ea3dc1927185e09b5254b6

test:
  secret_key_base: 3cae614d9e582c4c9f808e40430291682f675f910385b24585f0493e2820c1cc413fac3199f7aee35ca4ae5afeae68d1f3d187ba2b27d3ad38f46e9e1c6332ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
